// Generated by cpp11: do not edit by hand
// clang-format off

#include "episimR_types.h"
#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// transmission_time.cpp
doubles episimR_time_sample(int n, const transmission_time_R& ttr, interval_t t, int m);
extern "C" SEXP _episimR_episimR_time_sample(SEXP n, SEXP ttr, SEXP t, SEXP m) {
  BEGIN_CPP11
    return cpp11::as_sexp(episimR_time_sample(cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<const transmission_time_R&>>(ttr), cpp11::as_cpp<cpp11::decay_t<interval_t>>(t), cpp11::as_cpp<cpp11::decay_t<int>>(m)));
  END_CPP11
}
// transmission_time.cpp
doubles episimR_time_density(const transmission_time_R& ttr, doubles a1);
extern "C" SEXP _episimR_episimR_time_density(SEXP ttr, SEXP a1) {
  BEGIN_CPP11
    return cpp11::as_sexp(episimR_time_density(cpp11::as_cpp<cpp11::decay_t<const transmission_time_R&>>(ttr), cpp11::as_cpp<cpp11::decay_t<doubles>>(a1)));
  END_CPP11
}
// transmission_time.cpp
doubles episimR_time_hazardrate(const transmission_time_R& ttr, doubles a1);
extern "C" SEXP _episimR_episimR_time_hazardrate(SEXP ttr, SEXP a1) {
  BEGIN_CPP11
    return cpp11::as_sexp(episimR_time_hazardrate(cpp11::as_cpp<cpp11::decay_t<const transmission_time_R&>>(ttr), cpp11::as_cpp<cpp11::decay_t<doubles>>(a1)));
  END_CPP11
}
// transmission_time.cpp
doubles episimR_time_survivalprobability(const transmission_time_R& ttr, doubles a1);
extern "C" SEXP _episimR_episimR_time_survivalprobability(SEXP ttr, SEXP a1) {
  BEGIN_CPP11
    return cpp11::as_sexp(episimR_time_survivalprobability(cpp11::as_cpp<cpp11::decay_t<const transmission_time_R&>>(ttr), cpp11::as_cpp<cpp11::decay_t<doubles>>(a1)));
  END_CPP11
}
// transmission_time.cpp
doubles episimR_time_survivalquantile(const transmission_time_R& ttr, doubles a1);
extern "C" SEXP _episimR_episimR_time_survivalquantile(SEXP ttr, SEXP a1) {
  BEGIN_CPP11
    return cpp11::as_sexp(episimR_time_survivalquantile(cpp11::as_cpp<cpp11::decay_t<const transmission_time_R&>>(ttr), cpp11::as_cpp<cpp11::decay_t<doubles>>(a1)));
  END_CPP11
}
// transmission_time.cpp
transmission_time_R episimR_exponential_time(double lambda);
extern "C" SEXP _episimR_episimR_exponential_time(SEXP lambda) {
  BEGIN_CPP11
    return cpp11::as_sexp(episimR_exponential_time(cpp11::as_cpp<cpp11::decay_t<double>>(lambda)));
  END_CPP11
}
// transmission_time.cpp
transmission_time_R episimR_lognormal_time(double mean, double var, double pinf);
extern "C" SEXP _episimR_episimR_lognormal_time(SEXP mean, SEXP var, SEXP pinf) {
  BEGIN_CPP11
    return cpp11::as_sexp(episimR_lognormal_time(cpp11::as_cpp<cpp11::decay_t<double>>(mean), cpp11::as_cpp<cpp11::decay_t<double>>(var), cpp11::as_cpp<cpp11::decay_t<double>>(pinf)));
  END_CPP11
}
// transmission_time.cpp
transmission_time_R episimR_gamma_time(double mean, double var, double pinf);
extern "C" SEXP _episimR_episimR_gamma_time(SEXP mean, SEXP var, SEXP pinf) {
  BEGIN_CPP11
    return cpp11::as_sexp(episimR_gamma_time(cpp11::as_cpp<cpp11::decay_t<double>>(mean), cpp11::as_cpp<cpp11::decay_t<double>>(var), cpp11::as_cpp<cpp11::decay_t<double>>(pinf)));
  END_CPP11
}
// transmission_time.cpp
transmission_time_R episimR_generic_time(SEXP density, SEXP survivalprobability, bool probability_is_trinary, SEXP survivalquantile, bool quantile_is_trinary, SEXP sample, double pinfinity);
extern "C" SEXP _episimR_episimR_generic_time(SEXP density, SEXP survivalprobability, SEXP probability_is_trinary, SEXP survivalquantile, SEXP quantile_is_trinary, SEXP sample, SEXP pinfinity) {
  BEGIN_CPP11
    return cpp11::as_sexp(episimR_generic_time(cpp11::as_cpp<cpp11::decay_t<SEXP>>(density), cpp11::as_cpp<cpp11::decay_t<SEXP>>(survivalprobability), cpp11::as_cpp<cpp11::decay_t<bool>>(probability_is_trinary), cpp11::as_cpp<cpp11::decay_t<SEXP>>(survivalquantile), cpp11::as_cpp<cpp11::decay_t<bool>>(quantile_is_trinary), cpp11::as_cpp<cpp11::decay_t<SEXP>>(sample), cpp11::as_cpp<cpp11::decay_t<double>>(pinfinity)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_episimR_episimR_exponential_time",         (DL_FUNC) &_episimR_episimR_exponential_time,         1},
    {"_episimR_episimR_gamma_time",               (DL_FUNC) &_episimR_episimR_gamma_time,               3},
    {"_episimR_episimR_generic_time",             (DL_FUNC) &_episimR_episimR_generic_time,             7},
    {"_episimR_episimR_lognormal_time",           (DL_FUNC) &_episimR_episimR_lognormal_time,           3},
    {"_episimR_episimR_time_density",             (DL_FUNC) &_episimR_episimR_time_density,             2},
    {"_episimR_episimR_time_hazardrate",          (DL_FUNC) &_episimR_episimR_time_hazardrate,          2},
    {"_episimR_episimR_time_sample",              (DL_FUNC) &_episimR_episimR_time_sample,              4},
    {"_episimR_episimR_time_survivalprobability", (DL_FUNC) &_episimR_episimR_time_survivalprobability, 2},
    {"_episimR_episimR_time_survivalquantile",    (DL_FUNC) &_episimR_episimR_time_survivalquantile,    2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_episimR(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
