# Generated by cpp11: do not edit by hand

nextnetR_network_size <- function(nw) {
  .Call(`_NEXTNetR_nextnetR_network_size`, nw)
}

nextnetR_network_is_undirected <- function(nw) {
  .Call(`_NEXTNetR_nextnetR_network_is_undirected`, nw)
}

nextnetR_network_is_simple <- function(nw) {
  .Call(`_NEXTNetR_nextnetR_network_is_simple`, nw)
}

nextnetR_network_is_weighted <- function(nw) {
  .Call(`_NEXTNetR_nextnetR_network_is_weighted`, nw)
}

nextnetR_network_is_temporal <- function(nw) {
  .Call(`_NEXTNetR_nextnetR_network_is_temporal`, nw)
}

nextnetR_network_outdegree <- function(nw, nodes) {
  .Call(`_NEXTNetR_nextnetR_network_outdegree`, nw, nodes)
}

nextnetR_network_neighbour <- function(nw, nodes, indices) {
  .Call(`_NEXTNetR_nextnetR_network_neighbour`, nw, nodes, indices)
}

nextnetR_network_neighbour_weight <- function(nw, nodes, indices) {
  .Call(`_NEXTNetR_nextnetR_network_neighbour_weight`, nw, nodes, indices)
}

nextnetR_network_adjacencylist <- function(nw, above_diagonal) {
  .Call(`_NEXTNetR_nextnetR_network_adjacencylist`, nw, above_diagonal)
}

nextnetR_weighted_network_adjacencylist <- function(nw, above_diagonal) {
  .Call(`_NEXTNetR_nextnetR_weighted_network_adjacencylist`, nw, above_diagonal)
}

nextnetR_network_bounds <- function(nw) {
  .Call(`_NEXTNetR_nextnetR_network_bounds`, nw)
}

nextnetR_network_coordinates <- function(nw, nodes) {
  .Call(`_NEXTNetR_nextnetR_network_coordinates`, nw, nodes)
}

nextnetR_reproduction_matrix <- function(nw) {
  .Call(`_NEXTNetR_nextnetR_reproduction_matrix`, nw)
}

nextnetR_empirical_network <- function(path, undirected, simplify, idxbase, sep, gzip) {
  .Call(`_NEXTNetR_nextnetR_empirical_network`, path, undirected, simplify, idxbase, sep, gzip)
}

nextnetR_empirical_weightednetwork <- function(path, undirected, simplify, idxbase, csep, wsep, gzip) {
  .Call(`_NEXTNetR_nextnetR_empirical_weightednetwork`, path, undirected, simplify, idxbase, csep, wsep, gzip)
}

nextnetR_erdos_renyi_network <- function(size, avg_degree) {
  .Call(`_NEXTNetR_nextnetR_erdos_renyi_network`, size, avg_degree)
}

nextnetR_fully_connected_network <- function(size) {
  .Call(`_NEXTNetR_nextnetR_fully_connected_network`, size)
}

nextnetR_acyclic_network <- function(size, avg_degree, reduced_root_degree) {
  .Call(`_NEXTNetR_nextnetR_acyclic_network`, size, avg_degree, reduced_root_degree)
}

nextnetR_configmodel_network <- function(degrees) {
  .Call(`_NEXTNetR_nextnetR_configmodel_network`, degrees)
}

nextnetR_configmodel_clustered_alpha_network <- function(degrees, alpha, beta) {
  .Call(`_NEXTNetR_nextnetR_configmodel_clustered_alpha_network`, degrees, alpha, beta)
}

nextnetR_configmodel_clustered_ck_network <- function(degrees, ck, beta) {
  .Call(`_NEXTNetR_nextnetR_configmodel_clustered_ck_network`, degrees, ck, beta)
}

nextnetR_configmodel_clustered_triangles_network <- function(degrees, triangles, beta) {
  .Call(`_NEXTNetR_nextnetR_configmodel_clustered_triangles_network`, degrees, triangles, beta)
}

nextnetR_watts_strogatz_network <- function(size, k, p) {
  .Call(`_NEXTNetR_nextnetR_watts_strogatz_network`, size, k, p)
}

nextnetR_barabasialbert_network <- function(size, m) {
  .Call(`_NEXTNetR_nextnetR_barabasialbert_network`, size, m)
}

nextnetR_cubiclattice2d_network <- function(edge_length) {
  .Call(`_NEXTNetR_nextnetR_cubiclattice2d_network`, edge_length)
}

nextnetR_cubiclattice3d_network <- function(edge_length) {
  .Call(`_NEXTNetR_nextnetR_cubiclattice3d_network`, edge_length)
}

nextnetR_cubiclattice4d_network <- function(edge_length) {
  .Call(`_NEXTNetR_nextnetR_cubiclattice4d_network`, edge_length)
}

nextnetR_cubiclattice5d_network <- function(edge_length) {
  .Call(`_NEXTNetR_nextnetR_cubiclattice5d_network`, edge_length)
}

nextnetR_cubiclattice6d_network <- function(edge_length) {
  .Call(`_NEXTNetR_nextnetR_cubiclattice6d_network`, edge_length)
}

nextnetR_cubiclattice7d_network <- function(edge_length) {
  .Call(`_NEXTNetR_nextnetR_cubiclattice7d_network`, edge_length)
}

nextnetR_cubiclattice8d_network <- function(edge_length) {
  .Call(`_NEXTNetR_nextnetR_cubiclattice8d_network`, edge_length)
}

nextnetR_adjacencylist_network <- function(input_al, is_undirected, above_diagonal) {
  .Call(`_NEXTNetR_nextnetR_adjacencylist_network`, input_al, is_undirected, above_diagonal)
}

nextnetR_erdos_renyi_temporalnetwork <- function(size, avg_degree, timescale) {
  .Call(`_NEXTNetR_nextnetR_erdos_renyi_temporalnetwork`, size, avg_degree, timescale)
}

nextnetR_brownian_proximity_temporalnetwork <- function(size, avg_degree, radius, D0, D1, gamma, dt) {
  .Call(`_NEXTNetR_nextnetR_brownian_proximity_temporalnetwork`, size, avg_degree, radius, D0, D1, gamma, dt)
}

nextnetR_empirical_contact_temporalnetwork <- function(path, finite_duration, dt, gzip) {
  .Call(`_NEXTNetR_nextnetR_empirical_contact_temporalnetwork`, path, finite_duration, dt, gzip)
}

nextnetR_sirx_temporalnetwork <- function(nw, kappa0, kappa) {
  .Call(`_NEXTNetR_nextnetR_sirx_temporalnetwork`, nw, kappa0, kappa)
}

nextnetR_activity_driven_temporalnetwork <- function(activities_, m, eta_sus, eta_inf, b_sus, b_inf) {
  .Call(`_NEXTNetR_nextnetR_activity_driven_temporalnetwork`, activities_, m, eta_sus, eta_inf, b_sus, b_inf)
}

nextnetR_erdos_renyi_weightednetwork <- function(size, avg_degree, weights, probabilities) {
  .Call(`_NEXTNetR_nextnetR_erdos_renyi_weightednetwork`, size, avg_degree, weights, probabilities)
}

nextnetR_adjacencylist_weightednetwork <- function(input_al, is_undirected, above_diagonal) {
  .Call(`_NEXTNetR_nextnetR_adjacencylist_weightednetwork`, input_al, is_undirected, above_diagonal)
}

nextnetR_nextreaction_simulation <- function(nw, psi, rho_, opts) {
  .Call(`_NEXTNetR_nextnetR_nextreaction_simulation`, nw, psi, rho_, opts)
}

nextnetR_simulation_transmissiontime <- function(sim) {
  .Call(`_NEXTNetR_nextnetR_simulation_transmissiontime`, sim)
}

nextnetR_simulation_resettime <- function(sim) {
  .Call(`_NEXTNetR_nextnetR_simulation_resettime`, sim)
}

nextnetR_simulation_network <- function(sim) {
  .Call(`_NEXTNetR_nextnetR_simulation_network`, sim)
}

nextnetR_simulation_options <- function(sim) {
  .Call(`_NEXTNetR_nextnetR_simulation_options`, sim)
}

nextnetR_simulation_ninfected <- function(sim) {
  .Call(`_NEXTNetR_nextnetR_simulation_ninfected`, sim)
}

nextnetR_simulation_isinfected <- function(sim, nodes) {
  .Call(`_NEXTNetR_nextnetR_simulation_isinfected`, sim, nodes)
}

nextnetR_simulation_addinfections <- function(sim, nodes, times) {
  invisible(.Call(`_NEXTNetR_nextnetR_simulation_addinfections`, sim, nodes, times))
}

nextnetR_simulation_run <- function(sim_, stopconds, opts) {
  .Call(`_NEXTNetR_nextnetR_simulation_run`, sim_, stopconds, opts)
}

nextnetR_time_sample <- function(n, ttr, t, m) {
  .Call(`_NEXTNetR_nextnetR_time_sample`, n, ttr, t, m)
}

nextnetR_time_density <- function(ttr, taus, ts, ms) {
  .Call(`_NEXTNetR_nextnetR_time_density`, ttr, taus, ts, ms)
}

nextnetR_time_hazardrate <- function(ttr, taus) {
  .Call(`_NEXTNetR_nextnetR_time_hazardrate`, ttr, taus)
}

nextnetR_time_survivalprobability <- function(ttr, taus, ts, ms) {
  .Call(`_NEXTNetR_nextnetR_time_survivalprobability`, ttr, taus, ts, ms)
}

nextnetR_time_survivalquantile <- function(ttr, ps, ts, ms) {
  .Call(`_NEXTNetR_nextnetR_time_survivalquantile`, ttr, ps, ts, ms)
}

nextnetR_exponential_time <- function(lambda, pinf) {
  .Call(`_NEXTNetR_nextnetR_exponential_time`, lambda, pinf)
}

nextnetR_lognormal_time <- function(mean, var, pinf) {
  .Call(`_NEXTNetR_nextnetR_lognormal_time`, mean, var, pinf)
}

nextnetR_gamma_time <- function(mean, var, pinf) {
  .Call(`_NEXTNetR_nextnetR_gamma_time`, mean, var, pinf)
}

nextnetR_weibull_time <- function(shape, scale, pinf) {
  .Call(`_NEXTNetR_nextnetR_weibull_time`, shape, scale, pinf)
}

nextnetR_polynomial_rate_time <- function(coeffs) {
  .Call(`_NEXTNetR_nextnetR_polynomial_rate_time`, coeffs)
}

nextnetR_infectiousness_time <- function(taus, lambdas) {
  .Call(`_NEXTNetR_nextnetR_infectiousness_time`, taus, lambdas)
}

nextnetR_deterministic_time <- function(tau) {
  .Call(`_NEXTNetR_nextnetR_deterministic_time`, tau)
}

nextnetR_userdefined_time <- function(survival, density, sample, quantile, survival_accept_t_m, sample_accept_t_m, quantile_accept_t_m, p_infinity) {
  .Call(`_NEXTNetR_nextnetR_userdefined_time`, survival, density, sample, quantile, survival_accept_t_m, sample_accept_t_m, quantile_accept_t_m, p_infinity)
}
