# Generated by cpp11: do not edit by hand

episimR_time_sample <- function(n, ttr, t, m) {
  .Call(`_episimR_episimR_time_sample`, n, ttr, t, m)
}

episimR_time_density <- function(ttr, a1) {
  .Call(`_episimR_episimR_time_density`, ttr, a1)
}

episimR_time_hazardrate <- function(ttr, a1) {
  .Call(`_episimR_episimR_time_hazardrate`, ttr, a1)
}

episimR_time_survivalprobability <- function(ttr, a1) {
  .Call(`_episimR_episimR_time_survivalprobability`, ttr, a1)
}

episimR_time_survivalquantile <- function(ttr, a1) {
  .Call(`_episimR_episimR_time_survivalquantile`, ttr, a1)
}

episimR_exponential_time <- function(lambda) {
  .Call(`_episimR_episimR_exponential_time`, lambda)
}

episimR_lognormal_time <- function(mean, var, pinf) {
  .Call(`_episimR_episimR_lognormal_time`, mean, var, pinf)
}

episimR_gamma_time <- function(mean, var, pinf) {
  .Call(`_episimR_episimR_gamma_time`, mean, var, pinf)
}

episimR_generic_time <- function(density, survivalprobability, probability_is_trinary, survivalquantile, quantile_is_trinary, sample, pinfinity) {
  .Call(`_episimR_episimR_generic_time`, density, survivalprobability, probability_is_trinary, survivalquantile, quantile_is_trinary, sample, pinfinity)
}
